.TH LEISURE 1 "January 20, 2025" "2.1" "User Commands"
.SH NAME
leisure \- Consolidate media library browsing using fzf
.SH SYNOPSIS
.B leisure [-c \fI\,CONFIG_DIR\/\fR]
.SH DESCRIPTION
.TP
Browse book, film, game, and television libraries using fzf. Image previews supported under kitty.
.SH "SUPPORTED FILETYPES"
.TP
.B Books\fR
EPUB, PDF
.TP
.B Games\fR
Handled by runner
.TP
.B Video\fR
MKV, MP4
.SH OPTIONS
.TP
.B \-c
Specify a configuration directory
.TP
.B \-h
Display this message
.TP
.B \-n
Disable preview images
.TP
.B \-v
Display version number
.SH SUPPORTED RUNNERS
.TP
Emulators must be installed via flatpak.
.TP
\- BlastEm
.TP
\- bsnes
.TP
\- DeSmuME
.TP
\- Dolphin
.TP
\- Flycast
.TP
\- Heroic
.TP
\- Lutris
.TP
\- mGBA
.TP
\- Nestopia
.TP
\- PCSX2
.TP
\- PPSSPP
.TP
\- RPCS3
.TP
\- Steam
.SH FILES
CONFIG_DIR is $HOME/.config/leisure unless set to another directory using the -c flag.
.PP
.B $CONFIG_DIR/games.csv \fR- contains user-provided game entries, each including:
.RS 4
.TP
  \- Title
.TP
  \- Runner (The program being used to launch the game)
.TP
  \- ID or ROM filename
.RE
.TP
.B $CONFIG_DIR/paths.conf \fR- Used to configure media library paths.
.TP
.B $CONFIG_DIR/previews \fR- PNG files put in this directory will be used as preview images for titles with the same basename.
.SH "SEE ALSO" 
.BR fzf (1),
.BR kitty (1),
.BR flatpak (1), 
.BR mpv (1),
.BR zathura (1),
.BR awk (1)
